version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run:
                name: "Run Jest and Collect Coverage Reports"
                command: yarn test --collectCoverage=true
            - store_test_results:
                path: test-results
            - store_artifacts:
                path: coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test