version: 2
jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: "Install Expo"
          command: yarn global add expo-cli
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run:
          name: "Run Jest"
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - run: yarn cypress:ci
      - store_artifacts:
          path: /root/app/cypress/videos
      - store_artifacts:
          path: /root/app/cypress/screenshots
    parallelism: 4
