version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.7.0'
      - run: yarn
      - run:
          name: "Run Jest"
          command: yarn test
      - store_test_results:
          path: /tmp/test-results
    parallelism: 4
workflows:
    build-and-test:
      jobs:
        - build-and-test